name: "ssh-command-action"
description: "Github action for executing SSH command with the STDOUT returned as the output"

author: "Win"
inputs:
  host:
    description: "SSHPASS host"
    required: true
  port:
    description: "SSHPASS host"
    default: 22
  username:
    description: "SSHPASS username"
    required: true
  command:
    description: "command to be executed"
    required: true
  ssh_private_key:
    description: "private key to set up Public Key Authentication with SSH"
    required: true
outputs:
  command_execution_stdout:
    description: "The STDOUT resulted from the command execution"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    HOST: ${{ inputs.host }}
    PORT: ${{ inputs.port }}
    USERNAME: ${{ inputs.username }}
    COMMAND: ${{ inputs.command }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
