name: Test action

on:
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Execute sshpass
        uses: ./
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.PASSWORD}}
          command: ${{ secrets.COMMAND}}
